### ISSUE TITLE
Package it!

### ISSUE THREAD

**Issue by ocefpaf** [USGS-CMG/yaml2ncml#1]
- [x] setup.py
- [x] requirements.txt
- [x] test+CI
- [ ] register at PyPI
- [ ] docs

**Comment by ocefpaf** [comment]
We need better tests and better docs.  At the moment the docs are only CLI helper from `docopt`.

@rsignell-usgs Do you want to register it at PyPI?  If not we can close this one.

**Comment by rsignell-usgs** [comment]
I don't really want to register it at PyPI.
