### ISSUE TITLE
Refactor the ncml creation

### ISSUE THREAD

**Issue by ocefpaf** [USGS-CMG/yaml2ncml#10]
Right now ncml is create in via a convoluted call to several small text helper functions (`header`, `footer`, `write_grid_var`, `add_aggregation_scan`) and get/write fields functions (`str_att`, `add_global_atts`, `add_var_atts`)

I propose one "big string template" to substitute the text helper functions.

**Comment by rsignell-usgs** [comment]
"convoluted"?  You hurt my feelings.  :wink:

**Comment by ocefpaf** [comment]
Remember the bad programming but good design talk we had early today?  Your original design is good, simple, and hackable!  The good programming can comes afterwards :stuck_out_tongue_winking_eye: 

The worst case scenario is good programming buried deep in a bad design and step entry curve.

**Comment by rsignell-usgs** [comment]
Okay, I'm happy now:  I write easily understandable, functional and crappy code!  :smiley_cat:

**Comment by ocefpaf** [comment]
The main reason for re-factoring is to squash a bug.  I am experiencing a random failure when running the code on Python3.  Every now and then it complains that the `email` variable cannot be found in one of the helper functions.

**Comment by ocefpaf** [comment]
Scratch all of the above. I am working in a Jinja version for the templates that should be much cleaner and easier to use. Test PR soon...

**Comment by ocefpaf** [comment]
The bug was solved and the jinja template prototype already exists in #31. Closing this.
