### ISSUE TITLE
Update repository summary (and fix typo)

### ISSUE THREAD

**Issue by ocefpaf** [USGS-CMG/yaml2ncml#13]
Change 

`ROMS ncML aggregation from YAML especification`

to 

`NcML aggregation from YAML specification`

**Comment by rsignell-usgs** [comment]
@ocefpaf ,  I could fix the typo, but perhaps you could fix it and while you are there..... add a few sentences to https://github.com/rsignell-usgs/yaml2ncml/blob/master/README.rst about how to install and use the command line tool?

Also, why .rst instead of .md?  
I bet you have a reason...

**Comment by ocefpaf** [comment]
I cannot fix it the summary, but I can take care of the README in a PR.

> Also, why .rst instead of .md?

Both Markdown and ReST are rendered by GitHub, but PyPI only renders ReST.  That way, if we upload the package to PyPI, we will have a nice rendered page there too.

Otherwise we will end up with a PyPI page looking like [this](https://pypi.python.org/pypi/pyaxiom) instead of [this](https://pypi.python.org/pypi/ctd) :wink:

**Comment by rsignell-usgs** [comment]
Awesome!  Good to know!    I'll start writing .rst instead!

**Comment by ocefpaf** [comment]
> Awesome! Good to know! I'll start writing .rst instead!

Pro tip.  Keep writing markdown and then:
```bash
pandoc --from markdown_github <README_FILE> --to=rst
```

**Comment by ocefpaf** [comment]
@rsignell-usgs Note that the repository summary is still outdated!  Only you as the owner can fix that.

**Comment by ocefpaf** [comment]
The summary was re-written.  Closing this.
