### ISSUE TITLE
add fake vertical coordinate for bed thickness when sed Nbed is present

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/yaml2ncml#25]
As noted here: https://github.com/USGS-CMG/usgs-cmg-portal/issues/195, `bed_thickness` is not appearing in the portal.   This is because although these variables have a vertical dimension, they have no vertical coordinate variable, so the variables are not CF-compliant.

**Comment by rsignell-usgs** [comment]
We can fix this problem in NcML by adding a fake vertical coordinate variable for the bed:
```
     <variable name="Nbed" shape="Nbed" type="double">
      <attribute name="long_name" value="pseudo coordinate at seabed points"/>
      <attribute name="standard_name" value="ocean_sigma_coordinate"/>
      <attribute name="positive" value="up"/>
      <attribute name="formula_terms" value="sigma: Nbed eta: zeta depth: h"/>
      <values start="-1.0" increment="-0.01"/>
     </variable>
```
we need to have yaml2ncml write this into the file.

**Comment by ocefpaf** [comment]
This is done, right? Can we close it?
